steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: bash
    args:
      - -c
      - mkdir -p /workspace/_targets && mkdir -p /workspace/_targets/meta && gsutil
        -m cp -r gs://mark-edmondson-public-files/googleCloudRunner/_targets/meta
        /workspace/_targets || exit 0
    id: get previous _targets metadata
  - name: gcr.io/gcer-public/targets
    args:
      - Rscript
      - -e
      - targets::tar_make('file1')
    id: file1
    waitFor:
      - get previous _targets metadata
  - name: gcr.io/gcer-public/targets
    args:
      - Rscript
      - -e
      - targets::tar_make('input1')
    id: input1
    waitFor:
      - file1
  - name: gcr.io/gcer-public/targets
    args:
      - Rscript
      - -e
      - targets::tar_make('result1')
    id: result1
    waitFor:
      - input1
  - name: gcr.io/gcer-public/targets
    args:
      - Rscript
      - -e
      - targets::tar_make('result2')
    id: result2
    waitFor:
      - input1
  - name: gcr.io/gcer-public/targets
    args:
      - Rscript
      - -e
      - targets::tar_make('result3')
    id: result3
    waitFor:
      - input1
  - name: gcr.io/gcer-public/targets
    args:
      - Rscript
      - -e
      - targets::tar_make('result4')
    id: result4
    waitFor:
      - input1
  - name: gcr.io/gcer-public/targets
    args:
      - Rscript
      - -e
      - targets::tar_make('merge1')
    id: merge1
    waitFor:
      - result1
      - result2
      - result3
      - result4
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: bash
    args:
      - -c
      - date > buildtime.txt && gsutil cp buildtime.txt gs://mark-edmondson-public-files/googleCloudRunner/_targets/buildtime.txt
        && gsutil -m cp -r /workspace/_targets gs://mark-edmondson-public-files/googleCloudRunner
        && gsutil ls -r gs://mark-edmondson-public-files/googleCloudRunner
    id: Upload Artifacts
    waitFor:
      - merge1
#Generated by googleCloudRunner::cr_build_write at 2022-01-20 16:18:28
