steps:
- name: 'gcr.io/gcer-public/packagetools:master'
  id: Install Dependencies
  env:
  - 'CR_REGION=$_REGION'
  - 'GCE_DEFAULT_PROJECT_ID=$PROJECT_ID'
  - 'CR_BUILD_EMAIL=$_BUILD_EMAIL'
  - 'GCS_DEFAULT_BUCKET=$_BUCKET'
  args:
  - "Rscript"
  - "-e"
  - |
    library(devtools)
    install_dev_deps()
    library(goodpractice)
    library(covr)
    install_dev_deps()
    check()
    install()
    gp(checks = grep('(rcmdcheck|covr)', all_checks(), invert=TRUE, value=TRUE))
    pkgdown::build_site()

