steps:
- name: 'gcr.io/gcer-public/packagetools:master'
  id: Install Dependencies
  args:
  - "Rscript"
  - "-e"
  - |
    library(devtools)
    install_dev_deps()
    library(goodpractice)
    library(covr)
    install_dev_deps()
    Sys.setenv('CR_REGION'='$_REGION')
    Sys.setenv('GCE_DEFAULT_PROJECT_ID'='$PROJECT_ID')
    Sys.setenv('CR_BUILD_EMAIL'='$_BUILD_EMAIL')
    Sys.setenv('GCS_DEFAULT_BUCKET'='$_BUCKET')
    check()
    install()
    gp(checks = grep('(rcmdcheck|covr)', all_checks(), invert=TRUE, value=TRUE))
    codecov(line_exclusions = list('R/options.R', 'R/utilities.R', 'R/print_methods.R'))
- name: 'gcr.io/gcer-public/packagetools:master'
  id:  Deploy pkgdown site - wont work yet without git auth
  args: ["Rscript", "-e","pkgdown::build_site()"]

