steps:
- name: 'gcr.io/gcer-public/packagetools:master'
  id: Install Dependencies
  args: ["Rscript", "-e", "devtools::install_dev_deps()"]
- name: 'gcr.io/gcer-public/packagetools:master'
  id:  Check locally
  args: ["Rscript", "-e ","devtools::check()"]
- name: 'gcr.io/gcer-public/packagetools:master'
  id:  Install locally
  args: ["Rscript", "-e ","devtools::install()"]
- name: 'gcr.io/gcer-public/packagetools:master'
  id: Extra diagnostics
  args: ["Rscript",
         "-e",
         "goodpractice::gp(checks = grep('(rcmdcheck|covr)', goodpractice::all_checks(), invert=TRUE, value=TRUE))"]
- name: 'gcr.io/gcer-public/packagetools:master'
  id: Codecover
  args: ["Rscript", "-e",
         "library('covr');codecov(line_exclusions = list('R/options.R', 'R/utilities.R', 'R/print_methods.R'))"]
- name: 'gcr.io/gcer-public/packagetools:master'
  id:  Deploy pkgdown site - wont work yet without git auth
  args: ["Rscript", "-e ","pkgdown::build_site()"]

