steps:
- name: 'gcr.io/gcer-public/packagetools:master'
  id: Install Dependencies
  args:
  - "Rscript"
  - "-e"
  - |
    devtools::install_dev_deps()
    devtools::check()
    devtools::install()
    goodpractice::gp(checks = grep('(rcmdcheck|covr)', goodpractice::all_checks(), invert=TRUE, value=TRUE))
    library('covr');codecov(line_exclusions = list('R/options.R', 'R/utilities.R', 'R/print_methods.R'))
- name: 'gcr.io/gcer-public/packagetools:master'
  id:  Deploy pkgdown site - wont work yet without git auth
  args: ["Rscript", "-e","pkgdown::build_site()"]

