options:
  env:
  - 'CR_REGION=$_REGION'
  - 'GCE_DEFAULT_PROJECT_ID=$PROJECT_ID'
  - 'CR_BUILD_EMAIL=$_BUILD_EMAIL'
  - 'GCS_DEFAULT_BUCKET=$_BUCKET'
steps:
- name: 'gcr.io/gcer-public/packagetools:master'
  id: Build website
  args:
  - "Rscript"
  - "-e"
  - |
    devtools::install()
    pkgdown::build_site()
- name: 'gcr.io/cloud-builders/gcloud'
  id: decrypt gitkey
  args:
  - kms
  - decrypt
  - --ciphertext-file=github_rsa.enc
  - --plaintext-file=/root/.ssh/id_rsa
  - --location=global
  - --keyring=my-keyring
  - --key=github-key
  volumes:
  - name: 'ssh'
    path: /root/.ssh
# Set up git with key and domain
- name: 'gcr.io/cloud-builders/git'
  id: setup gitkey
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    chmod 600 /root/.ssh/id_rsa
    cat <<EOF >/root/.ssh/config
    Hostname github.com
    IdentityFile /root/.ssh/id_rsa
    EOF
    mv known_hosts /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Connect to the repository
- name: 'gcr.io/cloud-builders/git'
  id: push website
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    git commit -a -m='Build website: date +%Y-%m-%d_%H-%M-%S' \
    && git push git@github.com:$_GITHUB_REPO
  volumes:
  - name: 'ssh'
    path: /root/.ssh
